### ISSUE TITLE
PSA Warning not generated if deployments is changed by kubectl scale command

### ISSUE THREAD

**Issue by abhijit-dev82** [kubernetes/pod-security-admission#10]
On editing the deployment to change the replicas count for the deployment we observe as expected PSA warning message. As can be seen below.

root [ ~ ]# kubectl edit deploy nginx-lb-5 -n tkc-lb
Warning: would violate PodSecurity "restricted:latest": allowPrivilegeEscalation != false (container "nginx-lb-wl" must set securityContext.allowPrivilegeEscalation=false), unrestricted capabilities (container "nginx-lb-wl" must set securityContext.capabilities.drop=["ALL"]), runAsNonRoot != true (pod or container "nginx-lb-wl" must set securityContext.runAsNonRoot=true), seccompProfile (pod or container "nginx-lb-wl" must set securityContext.seccompProfile.type to "RuntimeDefault" or "Localhost")
deployment.apps/nginx-lb-5 edited

But the warning message is not seen or present in the audit , on using the "kubectl scale" command.
root[ ~ ]# kcl scale deploy nginx-lb-5 --replicas=2 -n tkc-lb
deployment.apps/nginx-lb-5 scaled

Namespace config
-------------------
```
root [ ~ ]# kubectl  get ns tkc-lb -o yaml
apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: "2023-06-14T13:07:26Z"
  labels:
    kubernetes.io/metadata.name: tkc-lb
    pod-security.kubernetes.io/enforce: privileged
  name: tkc-lb
  resourceVersion: "40550"
spec:
  finalizers:
  - kubernetes
status:
  phase: Active
```

AdmissionConfiguration
-----------------
```
apiVersion: apiserver.k8s.io/v1alpha1
kind: AdmissionConfiguration
plugins:
  - name: PodSecurity
    configuration:
      apiVersion: pod-security.admission.config.k8s.io/v1
      kind: PodSecurityConfiguration
      defaults:
        warn: "restricted"
        warn-version: "latest"
        audit: "restricted"
        audit-version: "latest"
      exemptions:
        namespaces: [kube-system, tkg-system, vmware-system-cloud-provider]
```

Is this a known issue?

**Comment by liggitt** [comment]
Warnings are only emitted when changing the deployment via a create/update of the primary resource. Scale modifies only the replicas field via a subresource, so the rest of the pod spec is not available to PSA to inspect / warn about

/close
