### ISSUE TITLE
automountServiceAccountToken to false?

### ISSUE THREAD

**Issue by samc1213** [kubernetes/pod-security-admission#12]
I am not deeply familiar with the scope of the pod security admission policies. However, it seems that setting `automountServiceAccountToken` to `true` (the default) on a pod spec can allow a pod to escalate privileges via kubernetes API access. Is there a reason there is not a rule for this pod spec configuration in the Pod Security Standards?

**Comment by joebowbeer** [comment]
According to its description, this repo implements the pod security standards (PSS), which do not include an automountServiceAccountToken restriction:

https://kubernetes.io/docs/concepts/security/pod-security-standards/

While I think the ability to restrict automountServiceAccountToken would be helpful in general purpose admission policy library, which this is apparently not, I don't think it would be feasible to enforce it in all namespaces at this time.

My reasoning aligns with that in this rejection of the idea in the nginx repo:

https://github.com/nginxinc/kubernetes-ingress/issues/3562#issuecomment-1436669229
