### ISSUE TITLE
Should the webhook's image be updated?

### ISSUE THREAD

**Issue by mamachanko** [kubernetes/pod-security-admission#13]
At the time of writing the webhook's image was updated 2 years ago by https://github.com/kubernetes/pod-security-admission/commit/7339f2432c1095924ffbcfa63181ee5cfb87ce63 to `1.25.0`. Have there been no new updates since or is it outdated?

**Comment by liggitt** [comment]
Since the built-in feature is GA in later kubernetes releases (all supported kubernetes versions at this point), there are no plans to update the standalone webhook image. If you want to build it yourself on later releases, the source is still available to do so.
