### ISSUE TITLE
policy/v1beta1 PodSecurityPolicy is deprecated in v1.21+, unavailable in v1.25+

### ISSUE THREAD

**Issue by yugandhar-btc** [kubernetes/pod-security-admission#5]
We are maintaining two one for default name space **pod_security_policy.yaml**  and one for istio **pod_security_policy-istio.yaml**,so as per the warring , PodSecurityPolicy will not be available in v1.25+

Could you please help us, how to migrate

Note:- we use terraform

**Comment by liggitt** [comment]
https://kubernetes.io/docs/tasks/configure-pod-container/migrate-from-psp/ has good information about migrating

You'll need to determine the permission level required for your pods, and ensure the namespaces containing those pods have at least that permission level. You can set that permission level by labeling the containing namespaces.
